### PR TITLE
Careers: Previous Job Vacancies

### PR DESCRIPTION
**Pull request by srmasharad**
### Changes
- added previous job vacancies section in **Careers Page**
- Fixed open vacancies list by checking if has `expired: false` or has no `expired` key in the  vacancy list
- Hide the **Submit My Job Application** button if the vacancy expired.
- Fixed: slider arrows `disabled`  when only a single item is in the slider.
- Updated content of **Careers Landing Page**

### CODE REVIEW

**Comment by acharyarupak391** [comment]
@srmasharad The card on previous job section is not scaling up on hover like in current job section. Is that intentional?

**Comment by srmasharad** [comment]
> 

Yes. Slider is overflow hidden and hover effects on cards may cutoffs and doesn't looks good.

**Comment by acharyarupak391** [comment]
> > 

Yes. Slider is overflow hidden and hover effects on cards may cutoffs and doesn't looks good.  

Got it

**Review by acharyarupak391 — APPROVED** [review]
Looks good to merge.

**Pull request closed without merging**
