### PR TITLE
Changed the dropdown UI of the language selector

### PR DESCRIPTION
**Pull request by mehta-meet**
- This PR is related to [this](https://app.clickup.com/t/220qc2x) clickup ticket
- Removed `@heroicons/react` package and added svgs wherever icon from that package were used

### CODE REVIEW

**Review by flashburst — CHANGES_REQUESTED** [review]
Please fix issues with the search and icons

**Comment by binodnpm** [comment]
Thank you for this PR. A couple of feedbacks:

1. Does not work in safari.
2. Padding and font size not pixel perfect or according to the design.
3. Width also not according to the design maybe because of ☝️ 2

**Comment by mehta-meet** [comment]
@binodnpm Can you share screenshots of safari. I don't have mac so won't be able to see what is not working. I will loo into point 2 and 3

**Comment by mehta-meet** [comment]
@flashburst  Resolved all the search and icon issues

**Comment by binodnpm** [comment]
All of my issues I reported remain unsolved @mehta-meet @flashburst

**Comment by binodnpm** [comment]
Overflow not handled properly.

Screen Shot 2022-02-21 at 1 25 44 PM

**Comment by mehta-meet** [comment]
@binodnpm I have resolved the issues mentioned by @flashburst . I will look into the issues mentioned by you and will  resolve it

**Comment by binodnpm** [comment]
Issues

1 Remove outline from the search textbox, looks weird in Safari
2 Padding and font size not pixel perfect or according to the design.
3 Width also not according to the design maybe because of ☝️ 2

**Comment by mehta-meet** [comment]
image
@binodnpm Resolved the scroll issues as shown in the image. The styling and font sizes are pixel matched with figma. I have added videos for that in the clickup as I am not able to add it over here.

As I can't run safari on my system I am not able to identify the problem. If you can share a screenshot it would be helpful for me to debug because I have removed the outline from the search box so it's weird that it's coming.

**Comment by mehta-meet** [comment]
Outline issue is fixed. Varun checked it on his device.

**Comment by binodnpm** [comment]
Is the difference in font sizes coming from design?

Screen Shot 2022-02-22 at 11 34 49 AM

**Pull request closed without merging**
